Add LDAP support
casdoor/casdoor-helm pull request #29
Opened 2024-10-03 16:53 UTC by baznikin

Application runs in container as non-root user and can't bind to lower port.
This PR adds ability to change LDAP port and expose it with Service.
Access to LDAP port from outside of K8s cluster is out of scope of this PR

2024-10-03 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor-helm?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor-helm?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor-helm?pullRequest=29) it.</sub>

2024-10-03 17:22 UTC, hsluoyz commented
@baznikin why so many code lines are changed?

2024-10-03 17:22 UTC, hsluoyz commented
@sp71 @MichaelSp plz review

2024-10-03 17:43 UTC, baznikin commented
> @baznikin why so many code lines are changed?

There are some minor imperfection - empty lines in generated YAML files. At first I decided to keep formating same way as you do, but later I noticed you simply miss `-` in some places and put it in others. So, I decide to fix formatting as well. Sorry, I forget to mention it

2024-10-04 00:54 UTC, hsluoyz commented
Formatting should be in separated PRs. One PR one thing

2024-10-04 08:11 UTC, baznikin commented
> Formatting should be in separated PRs. One PR one thing

You are right, fixed

2024-10-04 13:55 UTC, hsluoyz requested changes

2024-10-04 13:55 UTC, hsluoyz commented on charts/casdoor/values.yaml
> +    port: 10389
default is 389

2024-10-04 14:50 UTC, baznikin commented on charts/casdoor/values.yaml
> +    port: 10389
Yes, that's why it's not worked in container. Only root can bind to lower ports (<1024).
Let's bind inside container on some port of high range, and set port in Service to configurable value with default 139?

2024-10-04 14:51 UTC, baznikin commented on charts/casdoor/templates/deployment.yaml
> +          {{- if .Values.probe.liveness.enabled }}
missed this place when rollback format changes

2024-10-04 14:58 UTC, hsluoyz approved these changes

2024-10-04 15:01 UTC, merged